### ISSUE TITLE
Mistake in dolist?

### ISSUE THREAD

**Issue by mukundzare** [jakebox/jake-emacs#2]
```elisp
(dolist (mode '(help-mode-map
                  calendar-mode-map
                  (evil-define-key 'motion mode "q" 'kill-this-buffer))))
```
A right parens is missing after `calendar-mode-map`. Or am I reading it wrong?

**Comment by jakebox** [comment]
No, you're right. I have since removed this function, it wasn't quite working (unrelated to the missing parenthesis).

It's commented out here. https://github.com/jakebox/jake-emacs/blob/9cb0b48526c9682c56a803e48bd69da662e30ceb/jake-emacs/init.el#L359

Nice catch. I might return to this later.
